# Generated by Django 5.0.6 on 2024-05-28 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Məhsulun adı')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Məhsulun dəyəri')),
                ('quality', models.TextField(max_length=150, verbose_name='Məhsulun keyfiyyəti')),
                ('country', models.CharField(max_length=100, verbose_name='İxrac ölkəsi')),
                ('end_date', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Satıcı şirkət')),
            ],
        ),
    ]
