# Generated by Django 5.0.6 on 2024-06-03 21:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Article Images', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='products',
            name='quality',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Məhsulun keyfiyyəti'),
        ),
    ]
