# Generated by Django 5.0.6 on 2024-06-03 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_image_alter_products_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
    ]
